env:
  node: true
  es2021: true
  jest/globals: true

extends:
  - airbnb-base
  - prettier

plugins:
  - "@typescript-eslint"
  - jest

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 12
  sourceType: module

settings:
  import/resolver:
    node:
      extensions:
        - .ts

rules:
  import/extensions: "off"
  class-methods-use-this: "off"
