version: "3"

services:
  web:
    build: .
    container_name: node_starter_backend
    entrypoint: ["/src/entrypoint.sh"]
    ports: ["8000:8000"]
    env_file: [".env"]
    depends_on: ["db"]

  db:
    image: postgres
    env_file: [".env"]
    volumes: ["db_data:/var/lib/postgresql/data"]

volumes:
  db_data:
